#!/usr/bin/env node

/**
 * SQL Access MCP Server Installer
 * Automatically configures Claude Code and/or Claude Desktop to use this MCP server
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { homedir, platform } from 'os';

// ============================================================================
// Types
// ============================================================================

interface MCPServerEntry {
  command: string;
  args?: string[];
  env?: Record<string, string>;
}

interface MCPConfig {
  mcpServers?: Record<string, MCPServerEntry>;
  [key: string]: unknown;
}

interface InstallTarget {
  name: string;
  configPath: string;
  exists: boolean;
}

// ============================================================================
// Platform Detection
// ============================================================================

function getClaudeDesktopConfigPath(): string {
  const os = platform();
  const home = homedir();

  switch (os) {
    case 'darwin':
      return join(home, 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json');
    case 'win32':
      return join(
        process.env.APPDATA || join(home, 'AppData', 'Roaming'),
        'Claude',
        'claude_desktop_config.json'
      );
    default: // linux and others
      return join(home, '.config', 'Claude', 'claude_desktop_config.json');
  }
}

function getClaudeCodeConfigPath(): string {
  return join(homedir(), '.claude.json');
}

function getProjectRoot(): string {
  // Resolve from the install script's location (dist/install.js -> project root)
  const scriptDir = dirname(new URL(import.meta.url).pathname);
  return dirname(scriptDir);
}

function getDefaultSqlConfigPath(): string {
  // Default to config.ini in the project root
  return join(getProjectRoot(), 'config.ini');
}

// ============================================================================
// Config File Operations
// ============================================================================

function readJsonConfig(path: string): MCPConfig {
  if (!existsSync(path)) return {};
  try {
    const content = readFileSync(path, 'utf-8');
    return JSON.parse(content);
  } catch {
    return {};
  }
}

function writeJsonConfig(path: string, config: MCPConfig): void {
  const dir = dirname(path);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(path, JSON.stringify(config, null, 2) + '\n', 'utf-8');
}

function ensureConfigDir(configIniPath: string): void {
  const dir = dirname(configIniPath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function createDefaultConfigIni(path: string): void {
  const template = `; SQL Access MCP Server Configuration
; Generated by mcp-sql-install
; See documentation for full options: https://github.com/AraneaDev/sql-access

; Example database configuration (uncomment and edit):
; [database.mydb]
; type=postgresql
; host=localhost
; port=5432
; database=mydb
; username=myuser
; password=mypassword
; select_only=true
; mcp_configurable=true

[security]
max_joins=10
max_subqueries=5
max_unions=3
max_group_bys=5
max_complexity_score=100
max_query_length=10000

[extension]
max_rows=1000
max_batch_size=10
query_timeout=30000
`;
  ensureConfigDir(path);
  writeFileSync(path, template, 'utf-8');
}

// ============================================================================
// MCP Server Entry Builder
// ============================================================================

function buildMcpServerEntry(configIniPath: string): MCPServerEntry {
  const projectRoot = getProjectRoot();
  const entryPoint = join(projectRoot, 'dist', 'index.js');

  return {
    command: 'node',
    args: [entryPoint, '--config', configIniPath],
    env: {
      NODE_ENV: 'production',
    },
  };
}

// ============================================================================
// Installation Logic
// ============================================================================

function detectTargets(): InstallTarget[] {
  const targets: InstallTarget[] = [];

  const desktopPath = getClaudeDesktopConfigPath();
  targets.push({
    name: 'Claude Desktop',
    configPath: desktopPath,
    exists: existsSync(desktopPath) || existsSync(dirname(desktopPath)),
  });

  const codePath = getClaudeCodeConfigPath();
  targets.push({
    name: 'Claude Code',
    configPath: codePath,
    exists: existsSync(codePath),
  });

  return targets;
}

function installToTarget(
  target: InstallTarget,
  serverEntry: MCPServerEntry,
  dryRun: boolean
): boolean {
  const config = readJsonConfig(target.configPath);

  if (!config.mcpServers) {
    config.mcpServers = {};
  }

  const alreadyInstalled = !!config.mcpServers['sql-access'];
  config.mcpServers['sql-access'] = serverEntry;

  if (dryRun) {
    console.log(` [DRY RUN] Would write to ${target.configPath}:`);
    console.log(` ${JSON.stringify(config, null, 2).split('\n').join('\n ')}`);
    return true;
  }

  writeJsonConfig(target.configPath, config);

  if (alreadyInstalled) {
    console.log(` Updated existing sql-access entry in ${target.name}`);
  } else {
    console.log(` Added sql-access to ${target.name}`);
  }

  return true;
}

function uninstallFromTarget(target: InstallTarget, dryRun: boolean): boolean {
  if (!existsSync(target.configPath)) {
    console.log(` ${target.name}: config not found, skipping`);
    return false;
  }

  const config = readJsonConfig(target.configPath);
  if (!config.mcpServers?.['sql-access']) {
    console.log(` ${target.name}: sql-access not found, skipping`);
    return false;
  }

  delete config.mcpServers['sql-access'];

  if (dryRun) {
    console.log(` [DRY RUN] Would remove sql-access from ${target.configPath}`);
    return true;
  }

  writeJsonConfig(target.configPath, config);
  console.log(` Removed sql-access from ${target.name}`);
  return true;
}

// ============================================================================
// CLI
// ============================================================================

function parseArgs(): {
  client: 'claude-code' | 'claude-desktop' | 'both';
  configPath: string;
  dryRun: boolean;
  uninstall: boolean;
} {
  const args = process.argv.slice(2);
  let client: 'claude-code' | 'claude-desktop' | 'both' = 'both';
  let configPath = getDefaultSqlConfigPath();
  let dryRun = false;
  let uninstall = false;

  for (const arg of args) {
    if (arg.startsWith('--client=')) {
      const val = arg.split('=')[1];
      if (val === 'claude-code' || val === 'claude-desktop' || val === 'both') {
        client = val;
      } else {
        console.error(`Invalid --client value: ${val}. Use: claude-code, claude-desktop, both`);
        process.exit(1);
      }
    } else if (arg.startsWith('--config=')) {
      configPath = arg.split('=').slice(1).join('=');
    } else if (arg === '--dry-run') {
      dryRun = true;
    } else if (arg === '--uninstall') {
      uninstall = true;
    } else if (arg === '--help' || arg === '-h') {
      printHelp();
      process.exit(0);
    }
  }

  return { client, configPath, dryRun, uninstall };
}

function printHelp(): void {
  console.log(`
SQL Access MCP Server Installer

Usage:
 mcp-sql-install [options]

Options:
 --client=<target> Which client to configure (claude-code, claude-desktop, both)
 Default: both
 --config=<path> Path to config.ini for database configuration
 Default: ~/.config/sql-access/config.ini
 --dry-run Show what would be done without making changes
 --uninstall Remove sql-access from client configurations
 --help, -h Show this help message

Examples:
 mcp-sql-install # Install for all detected clients
 mcp-sql-install --client=claude-code # Install for Claude Code only
 mcp-sql-install --config=/path/to/config.ini # Use custom config path
 mcp-sql-install --dry-run # Preview changes
 mcp-sql-install --uninstall # Remove from all clients
`);
}

function main(): void {
  const { client, configPath, dryRun, uninstall } = parseArgs();

  console.log('');
  console.log('SQL Access MCP Server Installer');
  console.log('================================');
  console.log('');

  if (uninstall) {
    console.log('Uninstalling sql-access from MCP clients...');
    console.log('');

    const targets = detectTargets();
    const filtered = filterTargets(targets, client);
    let count = 0;

    for (const target of filtered) {
      if (uninstallFromTarget(target, dryRun)) count++;
    }

    console.log('');
    if (count === 0) {
      console.log('Nothing to uninstall.');
    } else {
      console.log(`Uninstalled from ${count} client(s).`);
    }
    return;
  }

  // Ensure config.ini exists
  if (!existsSync(configPath)) {
    console.log(`Creating default config at: ${configPath}`);
    if (!dryRun) {
      createDefaultConfigIni(configPath);
    } else {
      console.log(' [DRY RUN] Would create default config.ini');
    }
    console.log('');
  } else {
    console.log(`Using existing config: ${configPath}`);
    console.log('');
  }

  const serverEntry = buildMcpServerEntry(configPath);
  const targets = detectTargets();
  const filtered = filterTargets(targets, client);

  if (filtered.length === 0) {
    console.log('No installation targets found.');
    console.log('Specify --client=claude-code or --client=claude-desktop to force installation.');
    process.exit(1);
  }

  console.log('Installing to:');
  let successCount = 0;

  for (const target of filtered) {
    console.log(`\n ${target.name} (${target.configPath})`);
    if (installToTarget(target, serverEntry, dryRun)) {
      successCount++;
    }
  }

  console.log('');
  console.log('================================');

  if (dryRun) {
    console.log('DRY RUN complete. No changes were made.');
  } else {
    console.log(`Installation complete! (${successCount} client(s) configured)`);
    console.log('');
    console.log('Next steps:');
    console.log(` 1. Edit your database config: ${configPath}`);
    console.log(' 2. Restart Claude Code / Claude Desktop');
    console.log(' 3. The sql-access tools will be available automatically');
    console.log('');
    console.log('You can also add databases via MCP using the sql_add_database tool.');
  }
}

function filterTargets(targets: InstallTarget[], client: string): InstallTarget[] {
  if (client === 'both') {
    // When 'both', install to all targets (even if config doesn't exist yet, we create it)
    return targets;
  }
  if (client === 'claude-desktop') {
    return targets.filter((t) => t.name === 'Claude Desktop');
  }
  if (client === 'claude-code') {
    return targets.filter((t) => t.name === 'Claude Code');
  }
  return targets;
}

main();
